target 'chachaH5Design' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for chacha_Mac
  pod 'AFNetworking', '~> 3.1.0'
  pod 'SnapKit', :git => "https://github.com/SnapKit/SnapKit.git", :branch => "master"
  pod 'pop', :git => 'https://github.com/facebook/pop.git', :branch => "master"
end
